name: Auto Unzip
on: [push]
jobs:
  unzip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract ZIP file
        run: |
          unzip SJT-TOUR-TRAVEL.zip -d ./extracted-folder
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated unzip extraction"
          git push
